export const PACKAGE_LIST_REQUEST = 'PACKAGE_LIST_REQUEST'
export const PACKAGE_LIST_SUCCESS = 'PACKAGE_LIST_SUCCESS'
export const PACKAGE_LIST_FAIL = 'PACKAGE_LIST_FAIL'

export const PACKAGE_CREATE_REQUEST = 'PACKAGE_CREATE_REQUEST'
export const PACKAGE_CREATE_SUCCESS = 'PACKAGE_CREATE_SUCCESS'
export const PACKAGE_CREATE_FAIL = 'PACKAGE_CREATE_FAIL'
export const PACKAGE_CREATE_RESET = 'PACKAGE_CREATE_RESET'

export const PACKAGE_DELETE_REQUEST = 'PACKAGE_DELETE_REQUEST'
export const PACKAGE_DELETE_SUCCESS = 'PACKAGE_DELETE_SUCCESS'
export const PACKAGE_DELETE_FAIL = 'PACKAGE_DELETE_FAIL'