export const FREQUENCY_CREATE_REQUEST = 'FREQUENCY_CREATE_REQUEST'
export const FREQUENCY_CREATE_SUCCESS = 'FREQUENCY_CREATE_SUCCESS'
export const FREQUENCY_CREATE_FAIL = 'FREQUENCY_CREATE_FAIL'
export const FREQUENCY_CREATE_RESET = 'FREQUENCY_CREATE_RESET'

export const FREQUENCY_LIST_REQUEST = 'FREQUENCY_LIST_REQUEST'
export const FREQUENCY_LIST_SUCCESS = 'FREQUENCY_LIST_SUCCESS'
export const FREQUENCY_LIST_FAIL = 'FREQUENCY_LIST_FAIL'
export const FREQUENCY_LIST_RESET = 'FREQUENCY_LIST_RESET'

export const FREQUENCY_DELETE_REQUEST = 'FREQUENCY_DELETE_REQUEST'
export const FREQUENCY_DELETE_SUCCESS = 'FREQUENCY_DELETE_SUCCESS'
export const FREQUENCY_DELETE_FAIL = 'FREQUENCY_DELETE_FAIL'

export const FREQUENCY_UPDATE_REQUEST = 'FREQUENCY_UPDATE_REQUEST'
export const FREQUENCY_UPDATE_SUCCESS = 'FREQUENCY_UPDATE_SUCCESS'
export const FREQUENCY_UPDATE_FAIL = 'FREQUENCY_UPDATE_FAIL'
export const FREQUENCY_UPDATE_RESET = 'FREQUENCY_UPDATE_RESET'

export const FREQUENCY_DETAILS_REQUEST = 'FREQUENCY_DETAILS_REQUEST'
export const FREQUENCY_DETAILS_SUCCESS = 'FREQUENCY_DETAILS_SUCCESS'
export const FREQUENCY_DETAILS_FAIL = 'FREQUENCY_DETAILS_FAIL'
export const FREQUENCY_DETAILS_RESET = 'FREQUENCY_DETAILS_RESET'